name: Build SORA Control
on: [push]

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer

      - name: Build
        run: |
          cmake -B build -G Xcode \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 \
            -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" \
            -DJUCE_BUILD_EXTRAS=ON
          cmake --build build --config Release

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: SORA-Control-App
          path: build/SoraControl_artefacts/Release/*.app
