name: Build SORA Control
on: [push]

jobs:
  build:
    # Kita ganti ke macos-13 yang merupakan versi terakhir 
    # yang mendukung rakitan untuk macOS lama secara stabil
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          # Perintah tambahan untuk memaksa Xcode pakai SDK yang lebih rendah
          cmake -B build -G Xcode -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"
          cmake --build build --config Release

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: SORA-Control-App
          path: build/SoraControl_artefacts/Release/*.app
